name: Build and Deploy to Prod
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install

    - name: Build
      run: |
        ls
        npm run build --verbose:true --configuration=production --base-href=/PipelineTest/
    - name: Deploy 
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: dist/PipelineTest
